[package]
name = "toothpaste"
version = "0.3.3"
edition = "2018"
description = "A pastebin written in Rust"
license = "MIT"

[dependencies]
askama = { version = "~0.10", features = ["with-tide"]}
askama_tide = "~0.13"
async-std = { version = "~1.10", features = ["attributes"] }
chrono = { version = "~0.4", features = ["serde"] }
clru = "~0.5"
dotenv = "~0.15"
fast_log = "~1.3"
fnv = "~1.0"
futures = "~0.3"
http = "~0.2"
log = "~0.4"
nanoid = "~0.4"
rbatis =  { version = "~2.1" }
serde = { version = "~1.0", features = ["derive"] }
serde-aux = "~3.0"
serde_json = "~1.0"
structopt = "~0.3"
syntect = "~4.6"
tide = "~0.16"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
