[package]
name = "toothpaste"
version = "0.4.0"
edition = "2021"
description = "A pastebin written in Rust"
license = "MIT"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
axum = "0.6.1"
chrono = { version = "~0.4", features = ["serde"] }
clru = "~0.5"
dotenv = "~0.15"
entity = { path = "entity" }
fnv = "~1.0"
futures = "~0.3"
migration = { path = "migration" }
nanoid = "~0.4"
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
serde = { version = "1", features = ["derive"] }
serde-aux = "~3.0"
serde_json = "~1.0"
structopt = "~0.3"
syntect = "~4.6"
tera = "1.17.0"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.0", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
