[package]
name = "toothpaste"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.10", features = ["with-tide"]}
askama_tide = "0.13.0"
async-std = { version = "1.10", features = ["attributes"] }
chrono = { version = "0.4", features = ["serde"] }
clru = "0.5.0"
dotenv = "0.15.0"
fast_log="1.3"
fnv = "1.0.7"
futures = "0.3.17"
http = "0.2.4"
lazy_static = "1.4.0"
log = "0.4"
rbatis =  { version = "2.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
syntect = "4.6"
tide = "0.16.0"