[package]
name = "toothpaste"
version = "0.4.1"
edition = "2021"
description = "A pastebin written in Rust"
license = "MIT"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
aes-gcm-siv = "0.11.1"
axum = "0.7.4"
base64 = "0.22.0"
chrono = { version = "~0.4", features = ["serde"] }
clru = "0.6.1"
dotenv = "~0.15"
entity = { path = "entity" }
fnv = "~1.0"
futures = "~0.3"
migration = { path = "migration" }
nanoid = "~0.4"
rand = "0.8.5"
sea-orm = { version = "^0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
serde = { version = "1", features = ["derive"] }
serde-aux = "4.5.0"
serde_json = "~1.0"
structopt = "~0.3"
syntect = "5.2.0"
tera = "1.17.0"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.5.2", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
