[package]
name = "toothpaste"
version = "0.2.2"
edition = "2018"
description = "A pastebin written in Rust"
license = "MIT"

[dependencies]
askama = { version = "0.10", features = ["with-tide"]}
askama_tide = "0.13.0"
async-std = { version = "1.10", features = ["attributes"] }
chrono = { version = "0.4", features = ["serde"] }
clru = "0.5.0"
dotenv = "0.15.0"
fast_log="1.3"
fnv = "1.0.7"
futures = "0.3.17"
http = "0.2.4"
log = "0.4"
nanoid = "0.4.0"
rbatis =  { version = "2.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
structopt = "0.3.25"
syntect = "4.6"
tide = "0.16.0"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
